### PR TITLE
Improve accessibility and fix CSS issues

### LINKED ISSUE #177: Improve accessibility and SEO
- [ ] use `h1` tag only for top-level headings only
- [ ] use `h2`-`h6` tags for all articles 
- [ ] use `h2`-`h6` tags for all sections

### PR DESCRIPTION
**Pull request by ginifizz**
| Q             | A
| ------------- | ---
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| BC breaks?    | no
| Deprecations? | yes/no
| Tickets       | fixes #177
| License       | MIT
| Doc PR        | api-platform/docs#...

- Fixes CSS issue on some open source logos
- Fixes icon font issues on home schema
- Improves headings for accessibility

### CODE REVIEW

File: src/components/home/Cover.js [hunk 1]
```diff
@@ -9,10 +9,19 @@ const Cover = () => (
...
+          src={spider}
+          alt="spider"
+          width="256"
+          height="419"
+        />
       </div>
       <Logo className="cover__logo" />
-      <h2>REST and GraphQL framework to build modern API-driven projects</h2>
+      <h1 className="cover__title h2-like">
+        <strong className="accessibility__hidden-block">API PLATFORM :</strong>
```
Comment (alanpoulain) [inline src/components/home/Cover.js]:
```suggestion
        <strong className="accessibility__hidden-block">API PLATFORM:</strong>
```

Comment (ginifizz) [reply src/components/home/Cover.js]: French reflex ;)

**Comment by dunglas** [comment]
Thanks @ginifizz
